defaults:
  navisworks_exe: C:\Program Files\Autodesk\Navisworks Manage 2022\FileToolsTaskRunner.exe
  signal_max_workers: 9
  bim_agent_url: http://host.docker.internal:8000
  export_files: &id001
  - 01.Сборка_Общая.rvt
  - 02.Сборка_Архитектура.rvt
  - 03.1 Сборка_Конструктив.rvt
  - 03.3 Сборка_Конструктив и Инженерные сети.rvt
  - 04.1 Сборка_Коробка здания.rvt
  - 04.2 Сборка_Коробка здания и Инженерные сети.rvt
  - 05.Сборка_Отопление и Вентиляция.rvt
  - 06.Сборка_Водоснабжение и Водоотведение.rvt
  - 07.Сборка_Общая Инженерные сети.rvt
  - 99_AS.rvt
  - 99_SC.rvt
  xml_template: Проверка_файлов.xml
projects:
  KGN_GP5.2:
    name: Курган 5.2
    folder_name: KGN_GP5.2
    output_path: C:\Users\dved\Desktop\RVT_ETL_tests
    export:
      source_path: C:\Users\dved\Desktop\RVT_ETL_tests\KGN_GP5.2\02_NWD
      files: *id001
    signal:
      project_id: 78048844-62a6-47e6-9f99-f9869fd875e2
      folder_id: 285c6b6f-303c-4f09-b54f-427696956396
      filter: Сборка
  KGN_GP06:
    name: Курган ГП5.6
    folder_name: KGN_GP06
    output_path: C:\Users\dved\Desktop\RVT_ETL_tests
    export:
      source_path: C:\Users\dved\Desktop\RVT_ETL_tests\KGN_GP5.2\02_NWD
      files: *id001
    signal:
      project_id: Ввредите код project из ссылки
      folder_id: Ввредите код folder из ссылки
      filter: Сборка
  TMN_RTM_GP08:
    name: тюмень ритмы ГП08
    folder_name: TMN_RTM_GP08
    output_path: C:\Users\dved\Desktop\RVT_ETL_tests
    export:
      source_path: C:\Users\dved\Desktop\RVT_ETL_tests\TMN_RTM_GP08\02_NWD
      files: *id001
    signal:
      project_id: Ввредите код project из ссылки
      folder_id: Ввредите код folder из ссылки
      filter: Сборка
